spring:
  application:
    name: immobylette--api-photo
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:immobylette-photo}?currentSchema=${DB_SCHEMA:photo}
    username: ${DB_USER:postgre}
    password: ${DB_PASSWORD:fakesecret}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations:
      - classpath:db/init
      - classpath:db/migration
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate.ddl-auto: none
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    include-message: always

gcs:
  project-id: ${GCP_PROJECT_ID:immobylette}
  bucket-name: ${GCP_BUCKET_NAME:immobylette--photos}
  credentials-location: immobylette-credentials.json

auth:
  api-key: ${API_KEY:fakekey}
