name: CI/CD Immobylette Api Photo

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build Snapshot and Push
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || !(github.ref == 'refs/heads/main')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version-file: '.java-version'

      - name: Copy gcp credentials
        run: ls -la

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Format image name
        id: format-image-name
        run: |
          echo "Running on pr: ${{ steps.branch-names.outputs.current_branch }}"
          BRANCH_FORMATTED=$(echo "${{ steps.branch-names.outputs.current_branch }}" | sed 's/[^a-zA-Z0-9]/-/g' | tr '[:upper:]' '[:lower:]')
          echo "Branch : ${BRANCH_FORMATTED}" 
          echo "TAG_NAME=$BRANCH_FORMATTED" >> "$GITHUB_OUTPUT"

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/setup-gcloud@v0
        with:
          export_default_credentials: true
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker europe-west9-docker.pkg.dev

      - name: Build and Push Snapshot
        env:
          TAG_NAME: ${{ steps.format-image-name.outputs.TAG_NAME }}
        run: |
          echo "Building image for branch $TAG_NAME"
          docker build -t europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/immobylette--api-photo/immobylette--api-photo:$TAG_NAME .
          docker push europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/immobylette--api-photo/immobylette--api-photo:$TAG_NAME
  

  release:
    name: Build Release and Push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version-file: '.java-version'

      - name: Copy gcp credentials
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > immobylette-credentials.json

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Get prefix
        id: get_prefix
        run: |
          prefix=$(echo $(git show -s --format=%s) | cut -d'/' -f 1)")
          echo "Prefix: $prefix"
          echo "prefix=$prefix" >> "$GITHUB_OUTPUT"

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          echo "tag=$latest_tag" >> "$GITHUB_OUTPUT"

      - name: Determine version bump
        id: bump_version
        env:
          prefix: ${{ steps.get_prefix.outputs.prefix }}
          tag: ${{ steps.get_tag.outputs.tag }}
        run: |
          case $prefix in
            core)
              new_version=$(echo $tag | awk -F'.' '{print $1+1"."$2"."$3}')
              ;;
            feat)
              new_version=$(echo $tag | awk -F'.' '{print $1"."$2+1".0"}')
              ;;
            fix)
              new_version=$(echo $tag | awk -F'.' '{print $1"."$2"."$3+1}')
              ;;
            *)
              echo "Invalid prefix: $prefix"
              exit 1
              ;;
          esac
          echo "New version: $new_version"
          echo "TAG_NAME=$new_version" >> "$GITHUB_OUTPUT"

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/setup-gcloud@v0
        with:
          export_default_credentials: true
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker europe-west9-docker.pkg.dev

      - name: Build and Push Snapshot
        env:
          TAG_NAME: ${{ steps.bump_version.outputs.TAG_NAME }}
        run: |
          echo "Building image for branch $TAG_NAME"
          docker build -t europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/immobylette--api-photo/immobylette--api-photo:$TAG_NAME .
          docker push europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/immobylette--api-photo/immobylette--api-photo:$TAG_NAME

      - name: Set new tag
        run: |
          git tag ${{ steps.bump_version.outputs.TAG_NAME }}
          git push origin ${{ steps.bump_version.outputs.TAG_NAME }}
